### ISSUE TITLE
Storyblok visual editor not working with static website

### ISSUE THREAD

**Issue by seppegadeyne** [storyblok/storyblok-svelte-boilerplate#2]
When exporting the sapper / svelte boilerplate to static website. The exported static website doesn't support the visual editor anymore from Storyblok. It only works when the website is run in SSR. 

The static website should have the editor page also. 

Best regards, Seppe

**Comment by DominikAngerer** [comment]
Hey there.

Since the Visuel Editor itself needs your process to rebuild your page as we do not change your HTML and therefore a static site (as it is static) can't serve that. You can have two instances - one with the SSR for the live-preview and one for production build everytime the webhook triggers.

A more advanced documentation around the way the Visual Editor works is currently in the making.

Best
Dominik

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue!

@DominikAngerer thanks for reply, but, if you permite me, I would like to add some more informations.

@seppegadeyne, we figured out this boilerplate didn't export the `editor` with the `yarn export` command. So, we updated the package.json in the export script adding the `--entry editor`, like described [in the documentation](https://sapper.svelte.dev/docs#How_it_works). So, if you need to export the editor page as well, you need to add `--entry editor` in export command.

Lastly, in the Storyblok App, you need to replace the editor path to `<YOUR_DOMAIN>/editor/?path=` (notice the backslash at the end of the word editor).

That's all!

**Comment by seppegadeyne** [comment]
Hi, thanks @DominikAngerer and @emanuelgsouza for your support.
